name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Decoder
        run: |
          cd decoder
          mkdir build
          cd build
          cmake ../
          cmake --build .
      - name: Build Encoder
        run: |
          cd encoder
          mkdir build
          cd build
          cmake ../
          cmake --build .
      - name: Build Visualizer
        run: |
          cd visualizer
          mkdir build
          cd build
          cmake ../
          cmake --build .